version: "3.8"
services:
  app:
    container_name: app
    env_file: ./.env
    restart: unless-stopped
    build: .
    ports:
      - $APP_PORT_1:$APP_PORT_2
    stdin_open: true
    tty: true
    volumes:
      - ./:/app
  client:
    container_name: client
    env_file: ./.env
    depends_on:
      - app
    restart: unless-stopped
    build: client
    ports:
      - $CLIENT_PORT_1:$CLIENT_PORT_2
    stdin_open: true
    tty: true
    volumes:
      - ./client:/app
